# Generated by Django 5.1.15 on 2026-07-13 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aigenerationlog',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_logs', to='analysis.analysis'),
        ),
        migrations.AddField(
            model_name='aigenerationlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aigenerationlog',
            index=models.Index(fields=['-created_at'], name='ai_generati_created_f1b12e_idx'),
        ),
    ]
